import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import type { DatabaseCapabilities } from "../src/types.ts";

const DB_COMPAT_URL = "https://raw.githubusercontent.com/onmax/db-compat/main/packages/data/data.json";

const outputFile = fileURLToPath(new URL("../docs/1.guide/_capabilities-table.md", import.meta.url));

interface CompatTarget { dialect: string; driver: string; version: string }
interface CompatEntry { support: Record<string, { supported: boolean }> }
interface CompatData {
  __meta: { targets: Record<string, CompatTarget> };
  sql: {
    types: Record<string, CompatEntry>;
    transactions: Record<string, CompatEntry>;
  };
}

// Map db0 connector names to db-compat target IDs
const targetMapping: Record<string, string> = {
  "cloudflare-hyperdrive-postgresql": "hyperdrive-postgresql",
  "cloudflare-hyperdrive-mysql": "hyperdrive-mysql",
};

const db0Connectors = [
  "better-sqlite3", "sqlite3", "bun-sqlite", "node-sqlite", "libsql", "cloudflare-d1",
  "postgresql", "pglite", "cloudflare-hyperdrive-postgresql",
  "mysql2", "cloudflare-hyperdrive-mysql",
];

function toDb0Capabilities(data: CompatData, targetId: string): DatabaseCapabilities {
  const id = targetMapping[targetId] || targetId;
  const target = data.__meta.targets[id];
  const types = data.sql.types;
  const tx = data.sql.transactions;

  return {
    supportsJSON: types.type_json.support[id].supported,
    supportsBooleans: target.dialect !== "sqlite",
    supportsArrays: types.type_array.support[id].supported,
    supportsDates: types.type_date.support[id].supported,
    supportsUUIDs: types.type_uuid.support[id].supported,
    supportsTransactions: tx.BEGIN.support[id].supported,
    supportsBatch: tx.batch_atomicity.support[id].supported,
  };
}

const capabilityLabels: Record<keyof DatabaseCapabilities, string> = {
  supportsJSON: "JSON",
  supportsBooleans: "Bool",
  supportsArrays: "Array",
  supportsDates: "Date",
  supportsUUIDs: "UUID",
  supportsTransactions: "Tx",
  supportsBatch: "Batch",
};

const check = "✓";
const cross = "—";

function generateTable(connectorCapabilities: Record<string, DatabaseCapabilities>): string {
  const headers = ["Connector", ...Object.values(capabilityLabels)];
  const separator = headers.map((h) => ":".padEnd(h.length, "-") + ":");

  const rows = Object.entries(connectorCapabilities).map(([name, caps]) => {
    const cells = Object.keys(capabilityLabels).map((key) =>
      caps[key as keyof DatabaseCapabilities] ? check : cross,
    );
    return [name, ...cells];
  });

  const lines = [headers.join(" | "), separator.join("|"), ...rows.map((row) => row.join(" | "))];
  return lines.map((line) => `| ${line} |`).join("\n");
}

console.log("Fetching db-compat data...");
const data: CompatData = await fetch(DB_COMPAT_URL).then((r) => r.json());

const connectorCapabilities: Record<string, DatabaseCapabilities> = Object.fromEntries(
  db0Connectors.map((id) => [id, toDb0Capabilities(data, id)]),
);

const content = `<!-- Auto-generated by scripts/gen-capabilities-docs.ts from db-compat data. Do not edit manually. -->
${generateTable(connectorCapabilities)}
`;

await writeFile(outputFile, content, "utf8");
console.log("Generated capabilities table to", outputFile);
