import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { connectorCapabilities } from "../src/connectors/_internal/capabilities.ts";
import type { DatabaseCapabilities } from "../src/types.ts";

const outputFile = fileURLToPath(new URL("../docs/1.guide/_capabilities-table.md", import.meta.url));

const db0Connectors = [
  "better-sqlite3", "sqlite3", "bun-sqlite", "node-sqlite", "libsql", "cloudflare-d1",
  "postgresql", "pglite", "cloudflare-hyperdrive-postgresql",
  "mysql2", "planetscale", "cloudflare-hyperdrive-mysql",
];

const capabilityLabels: Record<keyof DatabaseCapabilities, string> = {
  supportsJSON: "JSON",
  supportsBooleans: "Bool",
  supportsArrays: "Array",
  supportsDates: "Date",
  supportsUUIDs: "UUID",
  supportsTransactions: "Tx",
  supportsBatch: "Batch",
};

const check = "✓";
const cross = "—";

function generateTable(connectorCapabilities: Record<string, DatabaseCapabilities>): string {
  const headers = ["Connector", ...Object.values(capabilityLabels)];
  const separator = headers.map((h) => ":".padEnd(h.length, "-") + ":");

  const rows = Object.entries(connectorCapabilities).map(([name, caps]) => {
    const cells = Object.keys(capabilityLabels).map((key) =>
      caps[key as keyof DatabaseCapabilities] ? check : cross,
    );
    return [name, ...cells];
  });

  const lines = [headers.join(" | "), separator.join("|"), ...rows.map((row) => row.join(" | "))];
  return lines.map((line) => `| ${line} |`).join("\n");
}

const orderedCapabilities: Record<string, DatabaseCapabilities> = Object.fromEntries(
  db0Connectors.map((id) => {
    const caps = connectorCapabilities[id];
    if (!caps) {
      throw new Error(`No capabilities mapping found for connector: ${id}`);
    }
    return [id, caps] as const;
  }),
);

const content = `<!-- Auto-generated by scripts/gen-capabilities-docs.ts from src/capabilities.ts. Do not edit manually. -->
${generateTable(orderedCapabilities)}
`;

await writeFile(outputFile, content, "utf8");
console.log("Generated capabilities table to", outputFile);
