import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { connectors, type ConnectorName } from "../src/_connectors.ts";
import { dialectCapabilities, getCapabilities } from "../src/capabilities.ts";
import type { DatabaseCapabilities } from "../src/types.ts";

const outputFile = fileURLToPath(
  new URL("../docs/1.guide/_capabilities-table.md", import.meta.url),
);

/**
 * Capabilities of every connector, mirroring its `dialect` and `capabilityOverrides`.
 *
 * Typed as an exhaustive `Record<ConnectorName, ...>` so that `pnpm test:types`
 * fails when a connector is added without a row here.
 */
const connectorCapabilities: Record<ConnectorName, DatabaseCapabilities> = {
  "better-sqlite3": dialectCapabilities.sqlite,
  sqlite3: dialectCapabilities.sqlite,
  "bun-sqlite": dialectCapabilities.sqlite,
  bun: dialectCapabilities.sqlite,
  "node-sqlite": dialectCapabilities.sqlite,
  sqlite: dialectCapabilities.sqlite,
  "libsql-core": dialectCapabilities.libsql,
  "libsql-node": dialectCapabilities.libsql,
  libsql: dialectCapabilities.libsql,
  "libsql-http": dialectCapabilities.libsql,
  "libsql-web": dialectCapabilities.libsql,
  "cloudflare-d1": getCapabilities("sqlite", { supportsTransactions: false }),
  postgresql: dialectCapabilities.postgresql,
  pglite: dialectCapabilities.postgresql,
  neon: dialectCapabilities.postgresql,
  "cloudflare-hyperdrive-postgresql": dialectCapabilities.postgresql,
  mysql2: dialectCapabilities.mysql,
  planetscale: dialectCapabilities.mysql,
  "cloudflare-hyperdrive-mysql": dialectCapabilities.mysql,
};

const capabilityLabels: Record<keyof DatabaseCapabilities, string> = {
  supportsJSON: "JSON",
  supportsBooleans: "Bool",
  supportsArrays: "Array",
  supportsDates: "Date",
  supportsUUIDs: "UUID",
  supportsTransactions: "Tx",
};

const check = "✓";
const cross = "—";

/** Canonical connector names, in registry order, with aliases removed. */
function canonicalConnectorNames(): ConnectorName[] {
  const seen = new Set<string>();
  return (Object.keys(connectors) as ConnectorName[]).filter((name) => {
    const subpath = connectors[name];
    if (seen.has(subpath)) {
      return false;
    }
    seen.add(subpath);
    return true;
  });
}

function generateTable(names: ConnectorName[]): string {
  const headers = ["Connector", ...Object.values(capabilityLabels)];
  const separator = headers.map((h) => ":".padEnd(h.length, "-") + ":");

  const rows = names.map((name) => {
    const caps = connectorCapabilities[name];
    const cells = (
      Object.keys(capabilityLabels) as (keyof DatabaseCapabilities)[]
    ).map((key) => (caps[key] ? check : cross));
    return [name, ...cells];
  });

  const lines = [
    headers.join(" | "),
    separator.join(" | "),
    ...rows.map((row) => row.join(" | ")),
  ];
  return lines.map((line) => `| ${line} |`).join("\n");
}

const content = `<!-- Auto-generated by scripts/gen-capabilities-docs.ts. Do not edit manually. -->
${generateTable(canonicalConnectorNames())}
`;

await writeFile(outputFile, content, "utf8");
console.log("Generated capabilities table to", outputFile);
