name: ci

on: { push: {}, pull_request: {} }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:types
      - run: pnpm vitest
