name: ci

on: { push: {}, pull_request: {} }

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm build
      - run: pnpm test:types
      - run: pnpm vitest
